services:
  postgres-db:
    image: postgres:15
    container_name: postgres-15
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ}
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
    platform: linux/x86_64
  redis:
    image: redis:7.4.3
    container_name: redis-wanted-7.4.3
    ports:
      - 6379:${REDIS_PORT}
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./db/redis/data:/data
      - ./db/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    labels:
      - 'name=redis'
      - 'mode=standalone'
    restart: always
  server-app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres-db
      - redis
    volumes:
      - ./server:/build/app
    expose:
      - 3000
    ports:
      - 3000:3000
    env_file:
      - .env.production
    restart: always
